# Default colors
[colors.primary]
background = '#000000'
foreground = '#9fffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#0000ff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#55ff55'
yellow  = '#ffff55'
blue    = '#5555ff'
magenta = '#ff55ff'
cyan    = '#55ffff'
white   = '#bbbbbb'
